### ISSUE TITLE
Nefit api returned invalid data

### ISSUE THREAD

**Issue by marcokeur** [marconfus/ha-nefit#7]
Just installed ha-nefit for my Nefit Easy. Startup of HA now takes a long time and results in a couple of error messages;

`
'utf-8' codec can't decode byte 0x94 in position 10: invalid start byte
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1708, in _event_runner
    func(*args)
  File "/usr/local/lib/python3.6/site-packages/nefit/__init__.py", line 96, in message
    response = self.decrypt(body)
  File "/usr/local/lib/python3.6/site-packages/nefit/__init__.py", line 155, in decrypt
    return self.encryption.decrypt(data)
  File "/usr/local/lib/python3.6/site-packages/nefit/__init__.py", line 36, in decrypt
    return decrypted.decode("utf8").rstrip(chr(0))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 10: invalid start byte`

and

`
Error processing event handler: <bound method NefitCore.message of <nefit.NefitClient object at 0x7faf05877da0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1708, in _event_runner
    func(*args)
  File "/usr/local/lib/python3.6/site-packages/nefit/__init__.py", line 96, in message
    response = self.decrypt(body)
  File "/usr/local/lib/python3.6/site-packages/nefit/__init__.py", line 155, in decrypt
    return self.encryption.decrypt(data)
  File "/usr/local/lib/python3.6/site-packages/nefit/__init__.py", line 36, in decrypt
    return decrypted.decode("utf8").rstrip(chr(0))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 10: invalid start byte`

Do you have any pointers on how to debug this any further?

**Comment by marconfus** [comment]
Hm, it could be possible that the credentials are not correct/accepted by the server.
Do you have any Python knowledge? Then you could dump the contents of the "body" variable before it gets decrypted. Perhaps it contains some error message in plain text.
You can also play around by using the nefit library (https://github.com/patvdleer/nefit-client-python) directly. It has some kind of command line client which can be used without homeassistant.

**Comment by marcokeur** [comment]
It turned out to be the case indeed, my password was wrong. Works as expected now, thanks!
