### ISSUE TITLE
Module not loading in home assistant 0.73.1

### ISSUE THREAD

**Issue by TimSoethout** [marconfus/ha-nefit#9]
Hi,

I'm using the latest version of `nefit-client` 0.2.5, but when starting home assistant with the `.py` from this repo I get this during launch:
```
Jul 16 22:15:16 odroid64 hass[8316]: 2018-07-16 22:15:16 ERROR (MainThread) [homeassistant.setup] Error during setup of component climate
Jul 16 22:15:16 odroid64 hass[8316]: Traceback (most recent call last):
Jul 16 22:15:16 odroid64 hass[8316]:   File "/opt/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 146, in _async_setup_component
Jul 16 22:15:16 odroid64 hass[8316]:     component.setup, hass, processed_config)  # type: ignore
Jul 16 22:15:16 odroid64 hass[8316]: AttributeError: module 'custom_components.climate' has no attribute 'setup'
```

Any pointers how to get it working? Google on this generic error indicates that something else of the configuration might be broken.

**Comment by TimSoethout** [comment]
It seems related to this:
https://github.com/home-assistant/home-assistant/issues/13269

Although I'm using 
```
$ python --version
Python 3.7.0
```

**Comment by TimSoethout** [comment]
If I put `nefit.py` in `/opt/homeassistant/lib/python3.7/site-packages/homeassistant/components/climate` it does load without errors... weird. probably has to do with some other `setup` not being in the `custom_components` folder.

Unfortunately I'm now running into 
```
Jul 16 23:53:18 odroid64 hass[18427]: 2018-07-16 23:53:18 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.heating is taking over 10 seconds
Jul 16 23:53:18 odroid64 hass[18427]: 2018-07-16 23:53:18 ERROR (event_thread_0) [sleekxmpp.xmlstream.xmlstream] Error processing event handler: <bound method NefitCore.message of <nefit.NefitClient object at 0x7f54dff7b8>>
Jul 16 23:53:18 odroid64 hass[18427]: Traceback (most recent call last):
Jul 16 23:53:18 odroid64 hass[18427]:   File "/opt/homeassistant/lib/python3.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1710, in _event_runner
Jul 16 23:53:18 odroid64 hass[18427]:     func(*args)
Jul 16 23:53:18 odroid64 hass[18427]:   File "/opt/homeassistant/lib/python3.7/site-packages/nefit/__init__.py", line 95, in message
Jul 16 23:53:18 odroid64 hass[18427]:     response = self.decrypt(body)
Jul 16 23:53:18 odroid64 hass[18427]:   File "/opt/homeassistant/lib/python3.7/site-packages/nefit/__init__.py", line 154, in decrypt
Jul 16 23:53:18 odroid64 hass[18427]:     return self.encryption.decrypt(data)
Jul 16 23:53:18 odroid64 hass[18427]:   File "/opt/homeassistant/lib/python3.7/site-packages/nefit/__init__.py", line 35, in decrypt
Jul 16 23:53:18 odroid64 hass[18427]:     return decrypted.decode("utf8").rstrip(chr(0))
Jul 16 23:53:18 odroid64 hass[18427]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 5: invalid start byte
Jul 16 23:53:18 odroid64 hass[18427]: 2018-07-16 23:53:18 ERROR (event_thread_0) [sleekxmpp.stanza.rootstanza] Error handling {jabber:client}message stanza
Jul 16 23:53:18 odroid64 hass[18427]: Traceback (most recent call last):
Jul 16 23:53:18 odroid64 hass[18427]:   File "/opt/homeassistant/lib/python3.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1710, in _event_runner
Jul 16 23:53:18 odroid64 hass[18427]:     func(*args)
Jul 16 23:53:18 odroid64 hass[18427]:   File "/opt/homeassistant/lib/python3.7/site-packages/nefit/__init__.py", line 95, in message
Jul 16 23:53:18 odroid64 hass[18427]:     response = self.decrypt(body)
Jul 16 23:53:18 odroid64 hass[18427]:   File "/opt/homeassistant/lib/python3.7/site-packages/nefit/__init__.py", line 154, in decrypt
Jul 16 23:53:18 odroid64 hass[18427]:     return self.encryption.decrypt(data)
Jul 16 23:53:18 odroid64 hass[18427]:   File "/opt/homeassistant/lib/python3.7/site-packages/nefit/__init__.py", line 35, in decrypt
Jul 16 23:53:18 odroid64 hass[18427]:     return decrypted.decode("utf8").rstrip(chr(0))
Jul 16 23:53:18 odroid64 hass[18427]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 5: invalid start byte
Jul 16 23:53:18 odroid64 hass[18427]: 2018-07-16 23:53:18 ERROR (event_thread_0) [sleekxmpp.basexmpp] 'utf-8' codec can't decode byte 0x84 in position 5: invalid start byte
Jul 16 23:53:18 odroid64 hass[18427]: Traceback (most recent call last):
Jul 16 23:53:18 odroid64 hass[18427]:   File "/opt/homeassistant/lib/python3.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1710, in _event_runner
Jul 16 23:53:18 odroid64 hass[18427]:     func(*args)
Jul 16 23:53:18 odroid64 hass[18427]:   File "/opt/homeassistant/lib/python3.7/site-packages/nefit/__init__.py", line 95, in message
Jul 16 23:53:18 odroid64 hass[18427]:     response = self.decrypt(body)
Jul 16 23:53:18 odroid64 hass[18427]:   File "/opt/homeassistant/lib/python3.7/site-packages/nefit/__init__.py", line 154, in decrypt
Jul 16 23:53:18 odroid64 hass[18427]:     return self.encryption.decrypt(data)
Jul 16 23:53:18 odroid64 hass[18427]:   File "/opt/homeassistant/lib/python3.7/site-packages/nefit/__init__.py", line 35, in decrypt
Jul 16 23:53:18 odroid64 hass[18427]:     return decrypted.decode("utf8").rstrip(chr(0))
Jul 16 23:53:18 odroid64 hass[18427]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 5: invalid start byte
Jul 16 23:53:28 odroid64 hass[18427]: 2018-07-16 23:53:28 WARNING (SyncWorker_4) [homeassistant.components.climate.nefit] Nefit api returned invalid data
```
With both version `0.2.2` and `0.2.5` of `nefit-client`.

**Comment by TimSoethout** [comment]
Interestingly when using `nefit-client` from the command line, I can view the status of the heating.

**Comment by TimSoethout** [comment]
I think I solved it... After a lot of debugging, I found out that the decrypting didn't work because of a faulty key.
In then end I solved it by putting all the secrets between quotes (`'`). My guess is that one of my secrets was parsed as an integer.

```
climate:
  platform: nefit
  name: Heating
  serial: 'XXXXXXXXX'
  accesskey: 'xxxxxxxxx'
  password: 'xxxxxxxxx'
```
